name: "[개발] 잡 트리거 - 유저 서비스 일일 통계 배치"

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.BASE_URI_DEV }}/batch/job/execute/dailyStaticsJob
          method: POST
          bearerToken: ${{ secrets.BATCH_TOKEN_DEV }}
          contentType: application/json
